// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Opds2T073LUV3tN_OOxGsO43v0h4OyA',
    appId: '1:994687622769:web:5e7163de04ac9440abc5d0',
    messagingSenderId: '994687622769',
    projectId: 'birthday-calendar-386b5',
    authDomain: 'birthday-calendar-386b5.firebaseapp.com',
    storageBucket: 'birthday-calendar-386b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoo1LEIBmnldGVsSGtqD1vTo7XDwRck1U',
    appId: '1:994687622769:android:f96d4f26e85d37e1abc5d0',
    messagingSenderId: '994687622769',
    projectId: 'birthday-calendar-386b5',
    storageBucket: 'birthday-calendar-386b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPb0njCOPbTsgJEZBhgbjHqxuqW887k4',
    appId: '1:994687622769:ios:8c1ce835b724d0a8abc5d0',
    messagingSenderId: '994687622769',
    projectId: 'birthday-calendar-386b5',
    storageBucket: 'birthday-calendar-386b5.appspot.com',
    iosClientId: '994687622769-oqh91rfbh5a3r4ehjt50nni4t8h6mb3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bdayCalendar',
  );
}
